fail_fast: true
repos:

- repo: local
  hooks:
  - id: system
    name: Run Tests
    entry: ./.venv/bin/python -m pytest
    pass_filenames: false
    language: system

- repo: local
  hooks:
  - id: system
    name: Run Black
    entry: ./.venv/bin/black raindroppy/
    pass_filenames: false
    language: system

- repo: local
  hooks:
  - id: system
    name: Run Ruff
    entry: ./.venv/bin/ruff --fix raindroppy/
    pass_filenames: false
    language: system
