fail_fast: true
repos:

- repo: local
  hooks:
  - id: system
    name: Running Tests
    entry: .venv/bin/python -m pytest
    pass_filenames: false
    language: system

- repo: local
  hooks:
  - id: system
    name: Running flake8
    entry: .venv/bin/flake8 raindroppy/
    pass_filenames: false
    language: system

- repo: local
  hooks:
  - id: system
    name: Running ssort
    entry: .venv/bin/ssort raindroppy/
    pass_filenames: false
    language: system

- repo: local
  hooks:
  - id: system
    name: Running isort
    entry: .venv/bin/isort raindroppy/
    pass_filenames: false
    language: system

- repo: local
  hooks:
  - id: system
    name: Running Black
    entry: .venv/bin/black raindroppy/
    pass_filenames: false
    language: system
