# .readthedocs.yaml
# Read the Docs configuration file.

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/confubar.py
   builder: html

python:
  install:
    - requirements: docs/requirements.txt
